sudo: required
language: scala
scala:
  - 2.12.4

cache:
  timeout: 600
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/build/peterbecich/NarrativeDemo/target

# before_install:
#   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#   - git submodule update --init --recursive
    
script:
  - sbt compile
  - sbt docker
    
jdk:
  - openjdk8

git:
  submodules: false
  
